#!/usr/bin/env bash
# Regression test: verifies CONTAINER_NAME is present in .env generated by prepare_env
# in scripts/init-environment.sh
# Issue: #733

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR="$(dirname "$SCRIPTS_DIR")"

PASS=0
FAIL=0

_pass() { echo "  PASS: $1"; PASS=$((PASS + 1)); }
_fail() { echo "  FAIL: $1"; FAIL=$((FAIL + 1)); }

# ---- setup tmp dir ----
TMP_DIR="$(mktemp -d)"
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

# ---- source naming library ----
# shellcheck disable=SC1091
source "${ROOT_DIR}/tools/worktree/lib/naming.sh"

# ===== PART A: Confirm bug in CURRENT init-environment.sh =====
echo "--- Part A: Confirm bug in current init-environment.sh ---"

# Extract prepare_env from init-environment.sh by grepping lines
# and test if CONTAINER_NAME is absent in the current implementation
CURRENT_PREPARE_ENV=$(grep -A 30 '^prepare_env\(\)' "${ROOT_DIR}/scripts/init-environment.sh")

if echo "$CURRENT_PREPARE_ENV" | grep -q "get_container_name"; then
    echo "  NOTE: get_container_name already called in prepare_env (bug may be fixed)"
    BUG_PRESENT=0
else
    echo "  BUG CONFIRMED: get_container_name not called in prepare_env"
    BUG_PRESENT=1
fi

if echo "$CURRENT_PREPARE_ENV" | grep -q "CONTAINER_NAME="; then
    echo "  NOTE: CONTAINER_NAME= already in prepare_env heredoc"
else
    echo "  BUG CONFIRMED: CONTAINER_NAME= missing from prepare_env heredoc"
fi

echo ""

# ===== PART B: Functional tests =====
echo "--- Part B: Functional tests ---"

cd "$TMP_DIR"

WORKTREE_NAME="feat-add-login-123"

# Call get_container_name and verify result
CONTAINER_NAME_VALUE=$(get_container_name "$WORKTREE_NAME")

# Test 1: CONTAINER_NAME value is non-empty
if [ -n "$CONTAINER_NAME_VALUE" ]; then
    _pass "get_container_name returns non-empty value: '$CONTAINER_NAME_VALUE'"
else
    _fail "get_container_name returns empty value"
fi

# Test 2: CONTAINER_NAME does NOT start with a hyphen
case "$CONTAINER_NAME_VALUE" in
    -*)
        _fail "CONTAINER_NAME starts with hyphen (invalid Docker container name): '$CONTAINER_NAME_VALUE'"
        ;;
    *)
        _pass "CONTAINER_NAME does not start with hyphen: '$CONTAINER_NAME_VALUE'"
        ;;
esac

# Test 3: CONTAINER_NAME matches expected sanitized branch name
EXPECTED=$(sanitize_branch_name "$WORKTREE_NAME")
if [ "$CONTAINER_NAME_VALUE" = "$EXPECTED" ]; then
    _pass "CONTAINER_NAME matches expected value: '$EXPECTED'"
else
    _fail "CONTAINER_NAME mismatch: got '$CONTAINER_NAME_VALUE', expected '$EXPECTED'"
fi

# Test 4: All 4 derived container names would be valid Docker names
for SUFFIX in db dev web api; do
    FULL_NAME="${CONTAINER_NAME_VALUE}-${SUFFIX}"
    # Docker requires names start with alphanumeric
    case "$FULL_NAME" in
        [a-zA-Z0-9]*)
            _pass "Container name '${FULL_NAME}' starts with alphanumeric (valid)"
            ;;
        *)
            _fail "Container name '${FULL_NAME}' does not start with alphanumeric (invalid)"
            ;;
    esac
done

# Test 5: WORKTREE_NAME=main produces valid CONTAINER_NAME
MAIN_CONTAINER_NAME=$(get_container_name "main")
if [ -n "$MAIN_CONTAINER_NAME" ]; then
    case "$MAIN_CONTAINER_NAME" in
        [a-zA-Z0-9]*)
            _pass "CONTAINER_NAME for 'main' worktree is valid: '$MAIN_CONTAINER_NAME'"
            ;;
        *)
            _fail "CONTAINER_NAME for 'main' starts with non-alphanumeric: '$MAIN_CONTAINER_NAME'"
            ;;
    esac
else
    _fail "CONTAINER_NAME for 'main' worktree is empty"
fi

# Test 6: CONTAINER_NAME is written to .env when using the fixed prepare_env
# Simulate the fixed prepare_env inline
WORKTREE_NAME2="fix-bug-init-environment-sh-733"
REPO_NAME=$(get_repo_name "$ROOT_DIR")
ENDPOINT_NAME="${WORKTREE_NAME2}.${REPO_NAME}"
DOCKER_PROJECT_NAME=$(sanitize_docker_project_name "$ENDPOINT_NAME")
CONTAINER_NAME2=$(get_container_name "$WORKTREE_NAME2")

cat > .env << ENVEOF
WORKTREE=${DOCKER_PROJECT_NAME}
ENDPOINT_NAME=${ENDPOINT_NAME}
COMPOSE_PROJECT_NAME=${DOCKER_PROJECT_NAME}
CONTAINER_NAME=${CONTAINER_NAME2}
HOST_WORKSPACE_PATH=${ROOT_DIR}
ENVEOF

if grep -q "^CONTAINER_NAME=" .env; then
    _pass "CONTAINER_NAME= line present in generated .env"
else
    _fail "CONTAINER_NAME= line missing from generated .env"
fi

ENV_CONTAINER_NAME=$(grep "^CONTAINER_NAME=" .env | cut -d'=' -f2-)
case "$ENV_CONTAINER_NAME" in
    -*)
        _fail "CONTAINER_NAME in .env starts with hyphen: '$ENV_CONTAINER_NAME'"
        ;;
    "")
        _fail "CONTAINER_NAME in .env is empty"
        ;;
    *)
        _pass "CONTAINER_NAME in .env is valid: '$ENV_CONTAINER_NAME'"
        ;;
esac

# ---- Summary ----
echo ""
echo "Results: ${PASS} passed, ${FAIL} failed"
if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
echo "All tests passed."
