#!/bin/bash
# PreToolUse hook for Write/Edit operations
# Blocks direct editing of code generator output directories
# Exit codes: 0 = allow, 2 = block, other = warning
#
# Input: JSON from stdin with tool_input.file_path
# Output: stderr message (shown to user if blocked)

set -euo pipefail

# Read JSON from stdin
INPUT=$(cat)

# Parse file path from JSON input
FILE_PATH=""
if [[ -n "$INPUT" ]]; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null || echo "")
  # Fall back to direct field
  if [[ -z "$FILE_PATH" ]]; then
    FILE_PATH=$(echo "$INPUT" | jq -r '.file_path // .path // empty' 2>/dev/null || echo "")
  fi
elif [[ -n "${CLAUDE_TOOL_INPUT:-}" ]]; then
  FILE_PATH=$(echo "$CLAUDE_TOOL_INPUT" | jq -r '.file_path // .path // empty' 2>/dev/null || echo "")
fi

# Python fallback if jq is not available
if [[ -z "$FILE_PATH" ]] && command -v python3 &>/dev/null && [[ -n "$INPUT" ]]; then
  FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    ti = data.get('tool_input', data)
    path = ti.get('file_path', '') or ti.get('path', '')
    print(path)
except:
    pass
" 2>/dev/null || echo "")
fi

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# === Block direct edits to code generator output directories ===
# These files are auto-generated and must not be edited directly.
# Use the appropriate generator command instead.

if [[ "$FILE_PATH" =~ /generated/ ]]; then
  echo "BLOCKED: Direct editing of generated code is forbidden." >&2
  echo "" >&2
  echo "File: $FILE_PATH" >&2
  echo "" >&2

  # Provide specific fallback instructions based on the path
  if [[ "$FILE_PATH" =~ /generated/oas/ ]] || \
     [[ "$FILE_PATH" =~ apps/api/src/generated ]]; then
    echo "These files are generated by hono-takibi from the OpenAPI spec." >&2
    echo "" >&2
    echo "Correct workflow:" >&2
    echo "  1. Edit the OpenAPI spec: projects/packages/api-contract/openapi.yaml" >&2
    echo "  2. Run: ./tools/contract openapi-generate" >&2
  elif [[ "$FILE_PATH" =~ api-contract/src/generated ]] || \
       [[ "$FILE_PATH" =~ packages/api-contract.*generated ]]; then
    echo "These files are generated by Orval from the OpenAPI spec." >&2
    echo "" >&2
    echo "Correct workflow:" >&2
    echo "  1. Edit the OpenAPI spec: projects/packages/api-contract/openapi.yaml" >&2
    echo "  2. Run: ./tools/contract openapi-generate" >&2
  elif [[ "$FILE_PATH" =~ prisma/generated ]]; then
    echo "These files are generated by Prisma from the schema." >&2
    echo "" >&2
    echo "Correct workflow:" >&2
    echo "  1. Edit the Prisma schema: projects/apps/api/prisma/schema.prisma" >&2
    echo "  2. Run: ./tools/contract migrate" >&2
  else
    echo "Use the appropriate code generator instead of editing directly:" >&2
    echo "" >&2
    echo "  hono-takibi / Orval output: ./tools/contract openapi-generate" >&2
    echo "  Prisma output:              ./tools/contract migrate" >&2
  fi

  echo "" >&2
  echo "Reason: .claude/rules/02-backend.md - generated code protection" >&2
  exit 2
fi

# All checks passed
exit 0
